# Generated by Django 4.2 on 2024-05-17 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('user', 'email_id', 'company_name'), 'verbose_name': 'vendor', 'verbose_name_plural': 'vendors'},
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='vendors_vendor',
        ),
    ]
